---
# tasks file for ansible-role-minio-swarm

- name: "Generate visualizer.yml file"
  ansible.builtin.template:
    src: visualizer.yml.j2
    dest: /opt/visualizer.yml
  when: inventory_hostname in groups['swarm_manager'][0]

- name: "Init visualizer"
  community.docker.docker_stack:
    state: present
    name: visualizer
    compose:
      - /opt/visualizer.yml
  when: inventory_hostname in groups['swarm_manager'][0]

- name: "Generate minio-cluster.yml file"
  ansible.builtin.template:
    src: minio-cluster.yml.j2
    dest: /opt/minio-cluster.yml
  when: inventory_hostname in groups['swarm_manager'][0]

- name: "Generate nginx.conf file"
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /opt/nginx.conf
  when: inventory_hostname in groups['swarm_manager'][0]

- name: "Init swarm cluster minio"
  community.docker.docker_stack:
    state: present
    name: minio
    compose:
      - /opt/minio-cluster.yml
  when: inventory_hostname in groups['swarm_manager'][0]
