---
# tasks file for ansible-role-minio-swarm

- name: "Copy minio-pass file to swarm manager"
  ansible.builtin.copy:
    src: ./minio_root_pass.txt
    dest: /opt/minio_root_pass.txt

- name: "Generate minio-cluster.yml file"
  ansible.builtin.template:
    src: minio-cluster.yml.j2
    dest: /opt/minio-cluster.yml
  when: inventory_hostname in groups['swarm_manager'][0]

- name: "Generate nginx.conf file"
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /opt/nginx.conf
  when: inventory_hostname in groups['swarm_manager'][0]

- name: "Init swarm cluster minio"
  community.docker.docker_stack:
    state: present
    name: minio
    compose:
      - /opt/minio-cluster.yml
  when: inventory_hostname in groups['swarm_manager'][0]
